version: '3'

services:
  phoenix:
    image: bitwalker/alpine-elixir:latest
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: database_name
      PGPORT: 5432
      PGHOST: db
    command: '/bin/sh -c "while true; do sleep 2; done"'
    volumes:
      - ../:/mkhmac
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
 

  editor:
    image: ashimbel/u18dev:latest
    command: '/bin/sh -c "while true; do sleep 2; done"'
    volumes:
      - ../:/mkhmac
    depends_on:
      - db

volumes:
  pgdata:
